menu:
  - {name: 'Publications', url: '/publications'}
  - {name: 'Service', url: '/service'}
  - {name: 'Talks', url: '/talks'}
  - {name: 'Teaching', url: '/teaching'}
  - {name: 'CV', url: '/cv'}

# people:
# - {name: 'Primary Investigator', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}
# - {name: 'Lab Technician', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/lab-technician.jpg', url: 'lab-technician'}
# - {name: 'Graduate Student', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}

# courses:
# - {name: 'Vector Calculus', url: 'vector-calculus'}
# - {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
# - {name: 'Stellar Structures', url: 'stellar-structures'}

social:
- {icon: 'fab fa-github fa-3x', link: 'https://github.com/zeeraktalat'}
- {icon: 'fab fa-twitterfa-3x', link: 'https://twitter.com/zeeraktalat'}
- {icon: 'fab fa-linkedin fa-3x', link: 'https://www.linkedin.com/in/zeeraktalat/'}

contacts:
- {name: 'Dr. Zeerak Talat',
  title: 'Independent Scholar',
  department: 'Physics & Astronomy',
  institution: 'Independent Scholar',
  institution_address: '1 Main Street, Canada',
  email: 'zeerak_talat@sfu.ca',
  office: 'Science Building 505',
  image: 'assets/img/contact.jpg'}
